-- Enables trigram similarity, used to detect near-duplicate catalog names
-- below and later for the "did you mean?" fuzzy match on custom item entry.
create extension if not exists pg_trgm;

-- Seed data for catalog_items, parsed from the two research catalogs.
-- 734 rows after exact-duplicate collapse (see chat report for details).

insert into public.catalog_items
  (name, category, subcategory, is_perishable, is_returnable, suggested_price, barcode, brand, region)
values
('Garri (white cassava granules)', 'Staple/Flour', 'Swallow', false, true, 8.99, null, null, 'Nigeria'),
('Garri Ijebu (fine sour cassava granules)', 'Staple/Flour', 'Swallow', false, true, 12.99, null, null, 'Nigeria'),
('Yellow Garri (palm-oil cassava granules)', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Nigeria'),
('Elubo (yam flour, for amala)', 'Staple/Flour', 'Swallow', false, true, 14.99, null, null, 'Nigeria'),
('Poundo Yam / Pounded Yam flour', 'Staple/Flour', 'Swallow', false, true, 15.99, null, null, 'Nigeria'),
('Semovita / Golden Penny Semovita', 'Staple/Flour', 'Swallow', false, true, 9, null, 'Golden Penny', 'Nigeria'),
('Semolina flour', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Nigeria'),
('Lafun (fermented cassava flour)', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Nigeria'),
('Okpa / Bambara groundnut flour', 'Staple/Flour', 'Legume flour', false, true, 11.99, null, null, 'Nigeria'),
('Tapioca (cassava pearls)', 'Staple/Flour', 'Breakfast/Swallow', false, true, 7.99, null, null, 'Nigeria'),
('Beans flour (for moi moi / akara)', 'Staple/Flour', 'Legume flour', false, true, 10, null, null, 'Nigeria'),
('Plantain flour (for amala/plantain fufu)', 'Staple/Flour', 'Swallow', false, true, 12.99, null, null, 'Nigeria'),
('Wheat swallow flour', 'Staple/Flour', 'Swallow', false, true, 11.99, null, null, 'Nigeria'),
('Cocoyam flour', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Nigeria'),
('Rice flour (Ayoola)', 'Baking', 'Flour', false, true, 8.99, null, 'Ayoola', 'Nigeria'),
('Ofada rice (local unpolished rice)', 'Rice', 'Local rice', false, true, 18.99, null, null, 'Nigeria'),
('Abakaliki rice', 'Rice', 'Local rice', false, true, 24.99, null, 'Abakaliki', 'Nigeria'),
('Per Excellence parboiled rice, 25 lb', 'Rice', 'Parboiled', false, true, 38.99, null, null, 'Nigeria'),
('Mama Gold rice', 'Rice', 'Parboiled', false, true, 34.99, null, null, 'Nigeria'),
('Caprice / Royal Umbrella parboiled rice', 'Rice', 'Parboiled', false, true, 32.99, null, null, 'Nigeria'),
('Honey Beans (Oloyin)', 'Beans/Legumes', 'Beans', false, true, 16.99, null, null, 'Nigeria'),
('Black-eyed peas (white beans)', 'Beans/Legumes', 'Beans', false, true, 9.99, null, null, 'Nigeria'),
('Brown beans (Ewa oloyin)', 'Beans/Legumes', 'Beans', false, true, 14.99, null, null, 'Nigeria'),
('Bambara beans (Okpa seeds)', 'Beans/Legumes', 'Beans', false, true, 12.99, null, null, 'Nigeria'),
('Egusi (ground melon seeds)', 'Soup Ingredient', 'Thickener', false, true, 12.99, null, null, 'Nigeria'),
('Egusi (whole melon seeds)', 'Soup Ingredient', 'Thickener', false, true, 13.99, null, null, 'Nigeria'),
('Ogbono (wild mango seed, ground)', 'Soup Ingredient', 'Thickener', false, true, 12.99, null, null, 'Nigeria'),
('Iru / Locust beans (Dawadawa), whole', 'Condiment', 'Fermented', false, true, 6.99, null, null, 'Nigeria'),
('Iru / Locust beans, ground', 'Condiment', 'Fermented', false, true, 6.99, null, null, 'Nigeria'),
('Ogiri (fermented sesame/melon paste)', 'Condiment', 'Fermented', false, true, 8.99, null, null, 'Nigeria'),
('Ugba / Ukpaka (fermented oil bean)', 'Soup Ingredient', 'Fermented', true, false, 9.99, null, null, 'Nigeria'),
('Ground crayfish', 'Soup Ingredient', 'Dried seafood', false, true, 9.99, null, null, 'Nigeria'),
('Palm oil (red), Nina/Praise brand', 'Cooking Oil', 'Palm oil', false, true, 12.99, null, 'Nina', 'Nigeria'),
('Bleached palm oil', 'Cooking Oil', 'Palm oil', false, true, 12.99, null, null, 'Nigeria'),
('Banga / palm nut concentrate (cream)', 'Sauce/Paste', 'Palm', false, true, 4.99, null, null, 'Nigeria'),
('Pepper soup spice mix', 'Seasoning', 'Spice blend', false, true, 5.99, null, null, 'Nigeria'),
('Suya pepper (yaji spice)', 'Seasoning', 'Spice blend', false, true, 6.99, null, null, 'Nigeria'),
('Gino Jollof seasoning', 'Seasoning', 'Spice blend', false, true, 5, null, 'Gino', 'Nigeria'),
('Maggi cubes (crayfish/chicken)', 'Seasoning', 'Bouillon', false, true, 6.99, null, 'Maggi', 'Nigeria'),
('Knorr chicken cubes', 'Seasoning', 'Bouillon', false, true, 6.99, null, 'Knorr', 'Nigeria'),
('Cameroon pepper (ground)', 'Seasoning', 'Spice', false, true, 6.99, null, null, 'Nigeria'),
('Uda (Negro pepper pods)', 'Seasoning', 'Spice', false, true, 5.99, null, null, 'Nigeria'),
('Uziza seeds / leaves', 'Seasoning', 'Spice', false, true, 6.99, null, null, 'Nigeria'),
('Ehuru / Ariwo (calabash nutmeg)', 'Seasoning', 'Spice', false, true, 6.99, null, null, 'Nigeria'),
('De Rica tinned tomato paste', 'Canned/Jarred', 'Tomato base', false, true, 3, null, 'De Rica', 'Nigeria'),
('Gino tomato paste', 'Canned/Jarred', 'Tomato base', false, true, 2.49, null, 'Gino', 'Nigeria'),
('Titus sardines (in tomato)', 'Canned/Jarred', 'Fish', false, true, 3.99, null, 'Titus', 'Nigeria'),
('Geisha mackerel', 'Canned/Jarred', 'Fish', false, true, 3.49, null, 'Geisha', 'Nigeria'),
('Sauce So Good (pepper stew sauce)', 'Sauce/Paste', 'Cooking sauce', false, true, 9.99, null, null, 'Nigeria'),
('Nerrido stew sauce', 'Sauce/Paste', 'Cooking sauce', false, true, 9.99, null, null, 'Nigeria'),
('Ewedu (jute leaves), dried/frozen', 'Vegetables', 'Soup greens', true, false, 7, null, null, 'Nigeria'),
('Oha / Ora leaves', 'Vegetables', 'Soup greens', false, true, 6.99, null, null, 'Nigeria'),
('Ugu (fluted pumpkin leaves), dried', 'Vegetables', 'Soup greens', false, true, 6.99, null, null, 'Nigeria'),
('Bitterleaf (washed, dried)', 'Vegetables', 'Soup greens', false, true, 6.99, null, null, 'Nigeria'),
('Utazi leaves', 'Vegetables', 'Soup greens', false, true, 6.99, null, null, 'Nigeria'),
('Okazi / Afang leaves', 'Vegetables', 'Soup greens', false, true, 7.99, null, null, 'Nigeria'),
('Frozen spinach', 'Frozen', 'Vegetables', true, false, 6.99, null, null, 'Nigeria'),
('Abacha (cassava shreds, African salad)', 'Snacks/Staple', 'Cassava', false, true, 5, null, null, 'Nigeria'),
('Goat meat (frozen)', 'Frozen', 'Meat', true, false, 18.99, null, null, 'Nigeria'),
('Ponmo (cow skin)', 'Frozen', 'Meat', true, false, 12.99, null, null, 'Nigeria'),
('Cow foot (frozen)', 'Frozen', 'Meat', true, false, 14.99, null, null, 'Nigeria'),
('Shaki (tripe), frozen', 'Frozen', 'Meat', true, false, 13.99, null, null, 'Nigeria'),
('Smoked/hard chicken (frozen)', 'Frozen', 'Poultry', true, false, 16.99, null, null, 'Nigeria'),
('Frozen snails (5 count)', 'Frozen', 'Seafood', true, false, 19.99, null, null, 'Nigeria'),
('Chin chin (Feldos)', 'Snacks', 'Fried dough', false, true, 5.99, null, 'Feldos', 'Nigeria'),
('Kuli-kuli (peanut sticks)', 'Snacks', 'Peanut', false, true, 7.99, null, null, 'Nigeria'),
('Coated peanuts (peanut burger)', 'Snacks', 'Peanut', false, true, 8, null, null, 'Nigeria'),
('Plantain chips (Go-chips)', 'Snacks', 'Plantain', false, true, 3.99, null, 'Go-chips', 'Nigeria'),
('Kokoro (maize snack)', 'Snacks', 'Corn', false, true, 5.99, null, null, 'Nigeria'),
('Dodo Ikire (spiced fried plantain snack)', 'Snacks', 'Plantain', false, true, 7.99, null, null, 'Nigeria'),
('Nigerian meat pie (frozen)', 'Frozen', 'Pastry', true, false, 8.99, null, null, 'Nigeria'),
('Puff-puff mix', 'Baking', 'Snack mix', false, true, 7.99, null, null, 'Nigeria'),
('Golden Morn (cereal)', 'Breakfast', 'Cereal', false, true, 9.99, null, 'Golden Morn', 'Nigeria'),
('Zobo / sorrel (dried hibiscus) drink leaves', 'Beverage', 'Herbal drink', false, true, 6.99, null, null, 'Nigeria'),
('Maltina (malt drink)', 'Beverage', 'Malt', false, true, 2.49, null, 'Maltina', 'Nigeria'),
('Vitamalt (malt drink)', 'Beverage', 'Malt', false, true, 2.49, null, 'Vitamalt', 'Nigeria'),
('Malta Guinness', 'Beverage', 'Malt', false, true, 2.99, null, 'Malta Guinness', 'Nigeria'),
('Amstel Malta', 'Beverage', 'Malt', false, true, 2.49, null, 'Amstel', 'Nigeria'),
('Milo (chocolate malt)', 'Beverage', 'Cocoa', false, true, 12.99, null, 'Milo', 'Nigeria'),
('Bournvita', 'Beverage', 'Cocoa', false, true, 11.99, null, 'Bournvita', 'Nigeria'),
('Peak evaporated/powdered milk', 'Dairy', 'Milk', false, true, 14.99, null, 'Peak', 'Nigeria'),
('Chivita/Hollandia juice', 'Beverage', 'Juice', false, true, 4.99, null, 'Hollandia', 'Nigeria'),
('Tigernut (kunun aya)', 'Snacks/Superfood', 'Tigernut', false, true, 8.99, null, null, 'Nigeria'),
('Fura (fermented millet balls)', 'Breakfast', 'Millet', true, false, 7.99, null, null, 'Nigeria'),
('Nunu (fermented milk)', 'Dairy', 'Fermented', true, false, 6.99, null, null, 'Nigeria'),
('Kilishi (spiced dried beef)', 'Snacks', 'Meat', false, true, 18.99, null, 'Kilishi', 'Nigeria'),
('Dankwa / dakuwa (groundnut-millet balls)', 'Snacks', 'Peanut', false, true, 7.99, null, null, 'Nigeria'),
('Banku (fermented corn & cassava dough)', 'Staple/Flour', 'Swallow', false, true, 7, null, null, 'Ghana'),
('Banku mix (flour)', 'Staple/Flour', 'Swallow', false, true, 8.99, null, null, 'Ghana'),
('Kenkey (Ga, fermented corn dumpling)', 'Staple', 'Swallow', true, false, 6.99, null, null, 'Ghana'),
('Kenkey (Fante)', 'Staple', 'Swallow', true, false, 6.99, null, null, 'Ghana'),
('Fufu flour (plantain & cassava)', 'Staple/Flour', 'Swallow', false, true, 8.99, null, null, 'Ghana'),
('Tuo Zaafi (TZ) flour', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Ghana'),
('Gari (Ghanaian special)', 'Staple/Flour', 'Swallow', false, true, 7.99, null, null, 'Ghana'),
('Cocoyam flour (for fufu)', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Ghana'),
('Waakye leaves (sorghum leaves, rice-&-beans dye)', 'Soup Ingredient', 'Dye/leaves', false, true, 7, null, null, 'Ghana'),
('Shito (black pepper/shrimp sauce)', 'Sauce/Paste', 'Chili condiment', false, true, 11.99, null, null, 'Ghana'),
('Shito mix (dry pepper blend)', 'Seasoning', 'Spice blend', false, true, 7.99, null, null, 'Ghana'),
('Palm nut cream / Trofai palm soup base', 'Sauce/Paste', 'Palm', false, true, 6.99, null, null, 'Ghana'),
('Dawadawa (fermented locust bean)', 'Condiment', 'Fermented', false, true, 6.99, null, null, 'Ghana'),
('Agushie (ground melon seed)', 'Soup Ingredient', 'Thickener', false, true, 12.99, null, null, 'Ghana'),
('Kelewele spice mix', 'Seasoning', 'Spice blend', false, true, 6.99, null, null, 'Ghana'),
('Ahomka green pepper sauce', 'Sauce/Paste', 'Condiment', false, true, 5.99, null, null, 'Ghana'),
('Nkatie cake / nkate cake (peanut brittle)', 'Snacks', 'Peanut', false, true, 5.99, null, null, 'Ghana'),
('Achomo / chin chin (Ghanaian)', 'Snacks', 'Fried dough', false, true, 5.99, null, null, 'Ghana'),
('Bofrot / boflot (doughnut) mix', 'Baking', 'Snack mix', false, true, 7.99, null, null, 'Ghana'),
('Sobolo (hibiscus drink) leaves', 'Beverage', 'Herbal', false, true, 6.99, null, null, 'Ghana'),
('Asana / brukina (fermented millet drink)', 'Beverage', 'Millet', true, false, 6.99, null, null, 'Ghana'),
('Milo (Ghana)', 'Beverage', 'Cocoa', false, true, 12.99, null, 'Milo', 'Ghana'),
('Ga kenkey', 'Staple', 'Swallow', true, false, 6.99, null, null, 'Ghana'),
('Ice kenkey (dessert drink)', 'Beverage', 'Corn dessert', true, false, 6.99, null, null, 'Ghana'),
('Alata / Anago black soap (Ghanaian)', 'Household/Beauty', 'Soap', false, true, 6.99, null, null, 'Ghana'),
('Attiéké (fermented cassava couscous), dried', 'Staple', 'Cassava couscous', false, true, 9.99, null, null, 'Ivory Coast'),
('Attiéké Marguerite (250g)', 'Staple', 'Cassava couscous', false, true, 8.99, null, null, 'Ivory Coast'),
('Thiakry / Dégué (millet couscous)', 'Staple/Breakfast', 'Millet', false, true, 9.99, null, null, 'Senegal'),
('Sankhal (Senegalese millet cereal)', 'Breakfast', 'Millet', false, true, 8.99, null, null, 'Senegal'),
('Riz brisé (broken rice)', 'Rice', 'Broken rice', false, true, 14.99, null, null, 'Senegal'),
('Netetou / Soumbara (fermented néré condiment)', 'Condiment', 'Fermented', false, true, 8.99, null, null, 'Senegal'),
('Yeet / Yète (fermented sea snail)', 'Soup Ingredient', 'Dried seafood', false, true, 12.99, null, null, 'Senegal'),
('Guedj (fermented dried fish)', 'Fish/Seafood', 'Dried fish', false, true, 11.99, null, null, 'Senegal'),
('Diég Bou Diar double tomato concentrate', 'Canned/Jarred', 'Tomato base', false, true, 5.99, null, null, 'Senegal'),
('Mama Futa palm oil (750g)', 'Cooking Oil', 'Palm oil', false, true, 9.99, null, 'Mama Futa', 'West Africa'),
('Baobab (bouye) powder', 'Superfood', 'Fruit powder', false, true, 9.99, null, null, 'Senegal'),
('Bissap (dried hibiscus)', 'Beverage', 'Herbal', false, true, 6.99, null, null, 'Senegal'),
('Foutou / plantain foutou flour', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Ivory Coast'),
('Placali (fermented cassava paste)', 'Staple', 'Swallow', false, true, 7.99, null, null, 'Ivory Coast'),
('Kedjenou spice base', 'Seasoning', 'Spice blend', false, true, 6.99, null, null, 'Ivory Coast'),
('Gnamakoudji (ginger juice) concentrate', 'Beverage', 'Ginger', false, true, 6.99, null, null, 'Ivory Coast'),
('Cassava leaf / plasas (frozen, ground)', 'Produce/Frozen', 'Soup greens', true, false, 9.99, null, null, 'Sierra Leone'),
('Potato greens (sweet potato leaf)', 'Produce/Frozen', 'Soup greens', true, false, 8.99, null, null, 'Liberia'),
('Krain krain / crain crain (jute leaf)', 'Produce', 'Soup greens', true, false, 7.99, null, null, 'Sierra Leone'),
('Sawa sawa (sorrel leaf)', 'Produce', 'Soup greens', true, false, 6.99, null, null, 'Sierra Leone'),
('Palm butter / palm cream sauce', 'Sauce/Paste', 'Palm', false, true, 13.5, null, null, 'Liberia'),
('Palm butter leaves (Kablai/Teaja)', 'Seasoning', 'Dried leaf', false, true, 6.99, null, null, 'Liberia'),
('Country rice (local red rice)', 'Rice', 'Local rice', false, true, 14.99, null, null, 'Sierra Leone'),
('Benne / beni seed (sesame)', 'Baking/Seed', 'Seed', false, true, 6.99, null, null, 'Sierra Leone'),
('Kanya / kanyah (peanut-gari sweet)', 'Snacks', 'Peanut', false, true, 8.99, null, null, 'Sierra Leone'),
('Dumboy (cassava paste)', 'Staple', 'Swallow', false, true, 7.99, null, null, 'Liberia'),
('Cocoyam fufu (Golden Tropics)', 'Staple/Flour', 'Swallow', false, true, 8, null, null, 'West Africa'),
('Fonio (precooked, white)', 'Staple/Grain', 'Ancient grain', false, true, 12.99, null, null, 'Guinea'),
('Black fonio', 'Staple/Grain', 'Ancient grain', false, true, 13.99, null, null, 'West Africa'),
('Soumbala / Sumbala (fermented néré)', 'Condiment', 'Fermented', false, true, 9.99, null, null, 'Mali'),
('Tô / Toh flour (millet/sorghum)', 'Staple/Flour', 'Swallow', false, true, 8.99, null, null, 'Burkina Faso'),
('Dèguè (millet-yogurt dessert mix)', 'Snacks/Dairy', 'Millet', false, true, 6.99, null, null, 'Mali'),
('Wagashi / Wara (Fulani cow-milk cheese)', 'Dairy', 'Fresh cheese', true, false, 11.99, null, null, 'Benin'),
('Akassa / Akoumé (fermented corn dough)', 'Staple', 'Swallow', true, false, 6.99, null, null, 'Benin'),
('Foufoumix (instant fufu)', 'Staple/Flour', 'Swallow', false, true, 8.99, null, null, 'Togo'),
('Chere / Chereh (steamed millet couscous)', 'Staple', 'Millet', false, true, 8.99, null, null, 'Gambia'),
('Benachin jollof base', 'Seasoning', 'Spice blend', false, true, 5.99, null, null, 'Gambia'),
('Djansang (soup thickener seeds)', 'Soup Ingredient', 'Thickener', false, true, 9.99, null, null, 'Cameroon'),
('Wonjo (dried hibiscus)', 'Beverage', 'Herbal', false, true, 6.99, null, null, 'Gambia'),
('Baobab leaf powder (for tô sauce)', 'Soup Ingredient', 'Leaf powder', false, true, 6.99, null, null, 'Burkina Faso'),
('Groundnut paste (for domoda/mafé)', 'Sauce/Paste', 'Peanut', false, true, 7.99, null, null, 'Gambia'),
('Atchomon (kuli-kuli variant)', 'Snacks', 'Peanut', false, true, 7.99, null, null, 'Benin'),
('Injera (teff fermented flatbread, ~10 ct)', 'Staple', 'Flatbread', true, false, 9.95, null, null, 'Ethiopia'),
('Teff flour (brown)', 'Baking', 'Flour', false, true, 12.99, null, null, 'Ethiopia'),
('Teff flour (white)', 'Baking', 'Flour', false, true, 13.99, null, null, 'Ethiopia'),
('Berbere (chili spice blend)', 'Seasoning', 'Spice blend', false, true, 9.75, null, null, 'Ethiopia'),
('Mitmita (bird''s eye chili blend)', 'Seasoning', 'Spice blend', false, true, 8.5, null, null, 'Ethiopia'),
('Shiro (chickpea powder), miten', 'Soup Ingredient', 'Legume powder', false, true, 7.95, null, null, 'Ethiopia'),
('Shiro Nech (white shiro)', 'Soup Ingredient', 'Legume powder', false, true, 7.5, null, null, 'Ethiopia'),
('Niter kibbeh (spiced clarified butter)', 'Cooking Oil/Fat', 'Ghee', true, false, 12.95, null, null, 'Ethiopia'),
('Sheno kibe (vegetable ghee)', 'Cooking Oil/Fat', 'Ghee', false, true, 19.5, null, null, 'Ethiopia'),
('Korerima (Ethiopian cardamom), ground', 'Seasoning', 'Spice', false, true, 8.95, null, null, 'Ethiopia'),
('Korerima, whole', 'Seasoning', 'Spice', false, true, 8.75, null, null, 'Ethiopia'),
('Mekelesha (finishing spice blend)', 'Seasoning', 'Spice blend', false, true, 8.75, null, null, 'Ethiopia'),
('Abesh / Abish (fenugreek)', 'Seasoning', 'Spice', false, true, 4.25, null, null, 'Ethiopia'),
('Besobela (Ethiopian holy basil)', 'Seasoning', 'Herb', false, true, 6.99, null, null, 'Ethiopia'),
('Kolo (roasted barley/grain snack)', 'Snacks', 'Roasted grain', false, true, 6.99, null, null, 'Ethiopia'),
('Genfo (barley porridge flour)', 'Breakfast', 'Porridge', false, true, 7.99, null, null, 'Ethiopia'),
('Bula (ensete starch)', 'Staple', 'Starch', false, true, 9.99, null, null, 'Ethiopia'),
('Senafitch (Ethiopian mustard)', 'Seasoning', 'Condiment', false, true, 5.99, null, null, 'Ethiopia'),
('Alicha kimem (mild spice blend)', 'Seasoning', 'Spice blend', false, true, 8.75, null, null, 'Ethiopia'),
('Awaze (berbere chili paste)', 'Sauce/Paste', 'Chili paste', false, true, 9.5, null, null, 'Ethiopia'),
('Yirgacheffe coffee beans', 'Beverage', 'Coffee', false, true, 18.99, null, null, 'Ethiopia'),
('Sidamo coffee beans', 'Beverage', 'Coffee', false, true, 17.99, null, null, 'Ethiopia'),
('Ethiopian frankincense (etan)', 'Household', 'Incense', false, true, 7.99, null, null, 'Ethiopia'),
('Barley flour', 'Baking', 'Flour', false, true, 6.99, null, null, 'Ethiopia'),
('Hilbet (fenugreek paste base)', 'Soup Ingredient', 'Legume', false, true, 7.99, null, null, 'Eritrea'),
('Duqet / dabo kolo (baked snack)', 'Snacks', 'Baked', false, true, 6.99, null, null, 'Ethiopia'),
('Xawaash (Somali spice blend)', 'Seasoning', 'Spice blend', false, true, 8.99, null, null, 'Somalia'),
('Canjeero / Anjero (sourdough pancake)', 'Staple', 'Flatbread', true, false, 7.99, null, null, 'Somalia'),
('Malawax / Malawah (sweet pancake)', 'Breakfast', 'Flatbread', true, false, 7.99, null, null, 'Somalia'),
('Sabaayad / Kimis (layered flatbread)', 'Staple', 'Flatbread', true, false, 7.99, null, null, 'Somalia'),
('Sambusa (frozen, beef/tuna)', 'Frozen', 'Pastry', true, false, 9.99, null, null, 'Somalia'),
('Bariis / basmati rice (for iskukaris)', 'Rice', 'Basmati', false, true, 24.99, null, null, 'Somalia'),
('Muqmad / Oodkac (dried spiced beef)', 'Snacks', 'Meat', false, true, 16.99, null, null, 'Somalia'),
('Xalwo (Somali halwa)', 'Snacks', 'Confection', false, true, 9.99, null, null, 'Somalia'),
('Shaah / Somali tea spice blend', 'Beverage', 'Tea', false, true, 6.99, null, null, 'Somalia'),
('Ugali / maize meal (Kenya)', 'Staple/Flour', 'Maize meal', false, true, 8.99, null, null, 'Kenya'),
('Royco Mchuzi Mix (beef/chicken)', 'Seasoning', 'Bouillon', false, true, 4.99, null, 'Royco', 'Kenya'),
('Pilau masala', 'Seasoning', 'Spice blend', false, true, 5.99, null, null, 'Kenya'),
('Sukuma wiki (collard greens), fresh', 'Produce', 'Greens', true, false, 3.99, null, null, 'Kenya'),
('Simsim (sesame seed)', 'Baking/Seed', 'Seed', false, true, 6.99, null, null, 'Kenya'),
('Omena / Dagaa (dried silver fish)', 'Fish/Seafood', 'Dried fish', false, true, 12.99, null, null, 'Kenya'),
('Ketepa tea', 'Beverage', 'Tea', false, true, 8.99, null, 'Ketepa', 'Kenya'),
('Blue Band margarine', 'Dairy', 'Spread', true, false, 6.99, null, 'Blue Band', 'Kenya'),
('Githeri (maize & beans mix)', 'Beans/Legumes', 'Mixed', false, true, 7.99, null, null, 'Kenya'),
('Matoke / Matooke (green cooking banana)', 'Produce', 'Plantain/banana', true, false, 4.99, null, null, 'Uganda'),
('Posho (maize flour, Uganda)', 'Staple/Flour', 'Maize meal', false, true, 8.99, null, null, 'Uganda'),
('Groundnut (odii) paste', 'Sauce/Paste', 'Peanut', false, true, 7.99, null, null, 'Uganda'),
('Mukene (dried silver fish, Uganda)', 'Fish/Seafood', 'Dried fish', false, true, 12.99, null, null, 'Uganda'),
('Ugali flour (sembe/dona), Tanzania', 'Staple/Flour', 'Maize meal', false, true, 8.99, null, null, 'Tanzania'),
('Mchuzi mix (Tanzania curry)', 'Seasoning', 'Spice blend', false, true, 5.99, null, null, 'Tanzania'),
('Africafé instant coffee', 'Beverage', 'Coffee', false, true, 9.99, null, 'Africafé', 'Tanzania'),
('Chai masala (spiced tea blend)', 'Beverage', 'Tea', false, true, 6.99, null, null, 'East Africa'),
('Isombe (cassava leaf), Rwanda', 'Produce/Frozen', 'Soup greens', true, false, 8.99, null, null, 'Rwanda'),
('Akabanga (chili oil)', 'Sauce/Paste', 'Chili', false, true, 7.99, null, null, 'Rwanda'),
('Wali wa nazi (coconut rice) mix', 'Rice', 'Coconut rice', false, true, 7.99, null, null, 'Kenya'),
('Mandazi mix', 'Baking', 'Snack mix', false, true, 6.99, null, null, 'East Africa'),
('Kombolcha / dried fish (South Sudan)', 'Fish/Seafood', 'Dried fish', false, true, 13.99, null, null, 'South Sudan'),
('Pondu / Saka-saka (cassava leaves), frozen', 'Produce/Frozen', 'Soup greens', true, false, 8.99, null, null, 'DR Congo'),
('Fumbwa (wild leaf), dried', 'Produce', 'Soup greens', false, true, 9.99, null, null, 'DR Congo'),
('Fufu ya manioc (cassava fufu flour)', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'DR Congo'),
('Foufou ya pempe (white cassava fufu)', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Congo'),
('Chikwangue / Kwanga (cassava loaf)', 'Staple', 'Swallow', true, false, 6.99, null, null, 'DR Congo'),
('Ndakala / Makayabu (dried/salt fish)', 'Fish/Seafood', 'Dried fish', false, true, 14.99, null, null, 'DR Congo'),
('Pili pili (hot pepper sauce)', 'Sauce/Paste', 'Chili', false, true, 6.99, null, null, 'DR Congo'),
('Mikate mix (Congolese doughnut)', 'Baking', 'Snack mix', false, true, 6.99, null, null, 'DR Congo'),
('Loso (rice for loso na madesu)', 'Rice', 'White rice', false, true, 24.99, null, null, 'DR Congo'),
('Madesu (beans)', 'Beans/Legumes', 'Beans', false, true, 8.99, null, null, 'DR Congo'),
('Eru / Okok (shredded wild leaf)', 'Produce', 'Soup greens', false, true, 9.99, null, null, 'Cameroon'),
('Njama njama (huckleberry leaves), dried', 'Produce', 'Soup greens', false, true, 8.99, null, null, 'Cameroon'),
('Bobolo / Miondo (cassava sticks)', 'Staple', 'Swallow', true, false, 7.99, null, null, 'Cameroon'),
('Water fufu (fermented cassava)', 'Staple', 'Swallow', true, false, 7.99, null, null, 'Cameroon'),
('Egusi pudding / ground egusi (Cameroon)', 'Soup Ingredient', 'Thickener', false, true, 12.99, null, null, 'Cameroon'),
('Kanwa (limestone/akanwu)', 'Soup Ingredient', 'Cooking salt', false, true, 3.99, null, null, 'Cameroon'),
('Cameroon white pepper (Penja)', 'Seasoning', 'Spice', false, true, 9.99, null, null, 'Cameroon'),
('Mbongo / mbongo tchobi spice', 'Seasoning', 'Spice blend', false, true, 8.99, null, null, 'Cameroon'),
('Ndolé (bitterleaf), washed', 'Produce', 'Soup greens', false, true, 7.99, null, null, 'Cameroon'),
('Kwacoco / cocoyam (grated)', 'Staple', 'Swallow', true, false, 7.99, null, null, 'Cameroon'),
('Soya spice (brochette/suya)', 'Seasoning', 'Spice blend', false, true, 6.99, null, null, 'Cameroon'),
('Folere / hibiscus (Cameroon)', 'Beverage', 'Herbal', false, true, 6.99, null, null, 'Cameroon'),
('Biltong (air-dried beef)', 'Snacks/Meat', 'Cured meat', true, false, 14.99, null, null, 'South Africa'),
('Droëwors (dried sausage)', 'Snacks/Meat', 'Cured meat', true, false, 14.99, null, null, 'South Africa'),
('Boerewors (fresh sausage), frozen', 'Frozen', 'Sausage', true, false, 16.99, null, null, 'South Africa'),
('Mrs. Ball''s Chutney (Original)', 'Sauce/Paste', 'Chutney', false, true, 8.99, null, 'Mrs. Ball''s', 'South Africa'),
('Ouma Rusks (buttermilk)', 'Snacks/Bakery', 'Rusks', false, true, 9.99, null, 'Ouma', 'South Africa'),
('Freshpak Rooibos tea', 'Beverage', 'Tea', false, true, 8.99, null, 'Freshpak', 'South Africa'),
('Aromat (all-purpose seasoning)', 'Seasoning', 'Seasoning', false, true, 6.99, null, 'Aromat', 'South Africa'),
('Nando''s Peri-Peri sauce', 'Sauce/Paste', 'Chili', false, true, 7.99, null, 'Nando''s', 'South Africa'),
('Mielie meal (maize meal, for pap)', 'Staple/Flour', 'Maize meal', false, true, 12.99, null, null, 'South Africa'),
('Chakalaka (canned relish)', 'Canned/Jarred', 'Relish', false, true, 4.99, null, null, 'South Africa'),
('Samp (dried corn kernels)', 'Staple', 'Corn', false, true, 7.99, null, null, 'South Africa'),
('Samp & beans (umngqusho)', 'Staple', 'Corn & beans', false, true, 8.99, null, null, 'South Africa'),
('Cremora (coffee creamer)', 'Dairy', 'Creamer', false, true, 8.99, null, 'Cremora', 'South Africa'),
('Simba chips (various)', 'Snacks', 'Chips', false, true, 4.99, null, 'Simba', 'South Africa'),
('Peppermint Crisp chocolate', 'Snacks', 'Confection', false, true, 3.99, null, null, 'South Africa'),
('Cadbury Lunch Bar', 'Snacks', 'Confection', false, true, 3.49, null, 'Cadbury', 'South Africa'),
('Bakers Tennis biscuits', 'Snacks', 'Biscuits', false, true, 5.99, null, 'Bakers', 'South Africa'),
('Five Roses tea', 'Beverage', 'Tea', false, true, 8.99, null, 'Five Roses', 'South Africa'),
('Mealie meal (Zimbabwe, roller meal)', 'Staple/Flour', 'Maize meal', false, true, 12.99, null, null, 'Zimbabwe'),
('Matemba / Kapenta (dried small fish), 500g', 'Fish/Seafood', 'Dried fish', false, true, 13.99, null, null, 'Zimbabwe'),
('Mazoe Orange Crush concentrate', 'Beverage', 'Cordial', false, true, 9.99, null, 'Mazoe', 'Zimbabwe'),
('Maheu / Mageu (fermented maize drink)', 'Beverage', 'Maize drink', false, true, 2.99, null, null, 'Zimbabwe'),
('Cerevita (breakfast cereal)', 'Breakfast', 'Cereal', false, true, 12.99, null, 'Cerevita', 'Zimbabwe'),
('Tanganda tea', 'Beverage', 'Tea', false, true, 8.99, null, 'Tanganda', 'Zimbabwe'),
('Pfuko Maheu', 'Beverage', 'Maize drink', false, true, 3.49, null, 'Pfuko', 'Zimbabwe'),
('Delele / derere (dried okra)', 'Produce', 'Soup greens', false, true, 6.99, null, null, 'Zimbabwe'),
('Nshima / mealie meal (Zambia)', 'Staple/Flour', 'Maize meal', false, true, 12.99, null, null, 'Zambia'),
('Chikanda (African polony)', 'Snacks', 'Prepared', true, false, 9.99, null, null, 'Zambia'),
('Kapenta (Zambia), dried', 'Fish/Seafood', 'Dried fish', false, true, 13.99, null, null, 'Zambia'),
('Thobwa (sweet maize/millet drink)', 'Beverage', 'Fermented', true, false, 3.49, null, null, 'Malawi'),
('Nsima flour (Malawi)', 'Staple/Flour', 'Maize meal', false, true, 12.99, null, null, 'Malawi'),
('Usipa (dried lake fish)', 'Fish/Seafood', 'Dried fish', false, true, 13.99, null, null, 'Malawi'),
('Piri-piri / peri-peri sauce', 'Sauce/Paste', 'Chili', false, true, 6.99, null, null, 'Mozambique'),
('Xima (maize meal, Mozambique)', 'Staple/Flour', 'Maize meal', false, true, 12.99, null, null, 'Mozambique'),
('Matapa (cassava leaf & coconut) base', 'Produce', 'Soup greens', true, false, 8.99, null, null, 'Mozambique'),
('Couscous (fine/medium)', 'Staple', 'Semolina', false, true, 6.99, null, null, 'Morocco'),
('Ras el hanout (spice blend)', 'Seasoning', 'Spice blend', false, true, 8.99, null, null, 'Morocco'),
('Harissa (chili paste), tube/jar', 'Sauce/Paste', 'Chili', false, true, 5.99, null, null, 'Tunisia'),
('Preserved lemons (beldi)', 'Canned/Jarred', 'Preserved', false, true, 8.99, null, null, 'Morocco'),
('Chermoula (marinade blend)', 'Seasoning', 'Spice blend', false, true, 6.99, null, null, 'Morocco'),
('Merguez sausage (frozen)', 'Frozen', 'Sausage', true, false, 13.99, null, null, 'North Africa'),
('Dukkah (nut & spice blend)', 'Seasoning', 'Spice blend', false, true, 7.99, null, null, 'Egypt'),
('Dukkah / d-a (Egyptian)', 'Seasoning', 'Spice blend', false, true, 7.99, null, null, 'Egypt'),
('Ful medames (canned fava beans)', 'Canned/Jarred', 'Legumes', false, true, 3.99, null, null, 'Egypt'),
('Molokhia (jute leaf), dried/frozen', 'Produce', 'Soup greens', true, false, 6.99, null, null, 'Egypt'),
('Za''atar (herb blend)', 'Seasoning', 'Spice blend', false, true, 7.99, null, null, 'North Africa'),
('Baharat (spice blend)', 'Seasoning', 'Spice blend', false, true, 7.99, null, null, 'North Africa'),
('Freekeh (roasted green wheat)', 'Staple/Grain', 'Grain', false, true, 8.99, null, null, 'Egypt'),
('Besar (Algerian spice blend)', 'Seasoning', 'Spice blend', false, true, 7.99, null, null, 'Algeria'),
('Smen (fermented preserved butter)', 'Cooking Oil/Fat', 'Preserved butter', true, false, 12.99, null, null, 'Morocco'),
('Argan oil (culinary)', 'Cooking Oil', 'Specialty oil', false, true, 18.99, null, null, 'Morocco'),
('Orange blossom water', 'Baking', 'Flavoring', false, true, 6.99, null, null, 'Morocco'),
('Rose water', 'Baking', 'Flavoring', false, true, 6.99, null, null, 'Morocco'),
('Msemen / rghaif (folded flatbread)', 'Staple/Bakery', 'Flatbread', true, false, 7.99, null, null, 'Morocco'),
('Kisra / gurassa (Sudanese flatbread)', 'Staple', 'Flatbread', true, false, 7.99, null, null, 'Sudan'),
('Aseeda (Sudanese porridge) flour', 'Staple/Flour', 'Porridge', false, true, 8.99, null, null, 'Sudan'),
('Weika (dried okra powder, Sudan)', 'Soup Ingredient', 'Thickener', false, true, 6.99, null, null, 'Sudan'),
('Shatta (Sudanese chili paste)', 'Sauce/Paste', 'Chili', false, true, 6.99, null, null, 'Sudan'),
('Dukkah sudani / crushed peanut spice', 'Seasoning', 'Spice blend', false, true, 6.99, null, null, 'Sudan'),
('Karkadeh (hibiscus, Sudan/Egypt)', 'Beverage', 'Herbal', false, true, 6.99, null, null, 'Sudan'),
('Halva (tahini confection)', 'Snacks', 'Confection', false, true, 7.99, null, null, 'North Africa'),
('Tahini (sesame paste)', 'Sauce/Paste', 'Sesame', false, true, 7.99, null, null, 'North Africa'),
('Ackee (canned, Grace)', 'Canned/Jarred', 'Vegetable/fruit', false, true, 12.99, null, 'Grace', 'Jamaica'),
('Saltfish (salted cod)', 'Fish/Seafood', 'Salted fish', false, true, 15.99, null, null, 'Jamaica'),
('Grace jerk seasoning (paste)', 'Seasoning', 'Marinade', false, true, 6.99, null, 'Grace', 'Jamaica'),
('Walkerswood jerk seasoning', 'Seasoning', 'Marinade', false, true, 7.99, null, 'Walkerswood', 'Jamaica'),
('Scotch bonnet pepper (fresh)', 'Produce', 'Pepper', true, false, 3.99, null, null, 'Jamaica'),
('Grace callaloo (canned)', 'Canned/Jarred', 'Greens', false, true, 4.99, null, 'Grace', 'Jamaica'),
('Grace coconut milk powder', 'Dairy', 'Coconut', false, true, 5.99, null, 'Grace', 'Jamaica'),
('Grace mackerel in tomato sauce', 'Canned/Jarred', 'Fish', false, true, 3.99, null, 'Grace', 'Jamaica'),
('Betapac curry powder', 'Seasoning', 'Curry', false, true, 5.99, null, 'Betapac', 'Jamaica'),
('Pickapeppa sauce', 'Sauce/Paste', 'Condiment', false, true, 6.99, null, 'Pickapeppa', 'Jamaica'),
('Scotch bonnet pepper sauce', 'Sauce/Paste', 'Chili', false, true, 5.99, null, null, 'Jamaica'),
('Grace hot pepper sauce', 'Sauce/Paste', 'Chili', false, true, 4.99, null, 'Grace', 'Jamaica'),
('Bammy (cassava flatbread)', 'Staple', 'Flatbread', true, false, 5.99, null, null, 'Jamaica'),
('Festival mix (sweet fried dumpling)', 'Baking', 'Snack mix', false, true, 6.99, null, null, 'Jamaica'),
('Hardough bread', 'Bakery', 'Bread', true, false, 5.99, null, null, 'Jamaica'),
('Spice bun (Easter bun)', 'Bakery', 'Bun', true, false, 7.99, null, null, 'Jamaica'),
('Tastee cheese (canned processed)', 'Dairy', 'Cheese', false, true, 9.99, null, null, 'Jamaica'),
('Jamaican beef patty (frozen)', 'Frozen', 'Pastry', true, false, 8.99, null, null, 'Jamaica'),
('Cornmeal (for turn cornmeal/pudding)', 'Staple/Flour', 'Cornmeal', false, true, 5.99, null, null, 'Jamaica'),
('Grace Irish Moss drink', 'Beverage', 'Sea moss', false, true, 3.49, null, 'Grace', 'Jamaica'),
('Supligen (vanilla/peanut/Irish moss)', 'Beverage', 'Meal supplement', false, true, 3.99, null, 'Supligen', 'Jamaica'),
('Nutrament (drink)', 'Beverage', 'Meal supplement', false, true, 3.49, null, 'Nutrament', 'Jamaica'),
('Ting (grapefruit soda)', 'Beverage', 'Soda', false, true, 2.49, null, 'Ting', 'Jamaica'),
('Pink Ting (grapefruit soda)', 'Beverage', 'Soda', false, true, 2.49, null, 'Ting', 'Jamaica'),
('D&G Kola Champagne soda', 'Beverage', 'Soda', false, true, 2.49, null, 'D&G', 'Jamaica'),
('D&G Ginger Beer soda', 'Beverage', 'Soda', false, true, 2.49, null, 'D&G', 'Jamaica'),
('Malta (D&G / Vitamalt)', 'Beverage', 'Malt', false, true, 2.49, null, 'Vitamalt', 'Jamaica'),
('Milo (Jamaica)', 'Beverage', 'Cocoa', false, true, 12.99, null, 'Milo', 'Jamaica'),
('Ovaltine', 'Beverage', 'Cocoa', false, true, 11.99, null, 'Ovaltine', 'Jamaica'),
('Horlicks', 'Beverage', 'Malt', false, true, 11.99, null, 'Horlicks', 'Jamaica'),
('Blue Mountain coffee (ground)', 'Beverage', 'Coffee', false, true, 34.99, null, null, 'Jamaica'),
('Sorrel (dried)', 'Beverage', 'Herbal', false, true, 6.99, null, null, 'Jamaica'),
('Irish moss / sea moss (raw dried)', 'Beverage/Superfood', 'Sea moss', false, true, 14.99, null, null, 'Jamaica'),
('Roots tonic / Magnum tonic wine', 'Beverage', 'Tonic', false, true, 4.99, null, null, 'Jamaica'),
('Bustamante backbone (coconut candy)', 'Snacks', 'Confection', false, true, 3.99, null, null, 'Jamaica'),
('Busta / paradise plum sweets', 'Snacks', 'Confection', false, true, 3.99, null, null, 'Jamaica'),
('Banana chips (St. Mary''s)', 'Snacks', 'Chips', false, true, 3.99, null, 'St. Mary''s', 'Jamaica'),
('Grater cake (coconut)', 'Snacks', 'Confection', false, true, 4.99, null, null, 'Jamaica'),
('Gizzada (coconut tart)', 'Snacks/Bakery', 'Pastry', true, false, 5.99, null, null, 'Jamaica'),
('Solomon Gundy (pickled fish paste)', 'Sauce/Paste', 'Fish paste', true, false, 6.99, null, 'Solo', 'Jamaica'),
('Browning (gravy browning)', 'Seasoning', 'Colorant', false, true, 4.99, null, null, 'Jamaica'),
('Jamaican rice & peas mix', 'Rice', 'Rice & beans', false, true, 4.99, null, null, 'Jamaica'),
('Gungo peas (canned)', 'Canned/Jarred', 'Legumes', false, true, 3.49, null, null, 'Jamaica'),
('Ackee (Royal Montego, brine)', 'Canned/Jarred', 'Vegetable/fruit', false, true, 11.99, null, 'Royal Montego', 'Jamaica'),
('Pholourie mix (split pea)', 'Baking', 'Snack mix', false, true, 5.99, null, null, 'Trinidad'),
('Doubles (bara + channa), frozen', 'Frozen', 'Street food', true, false, 8.99, null, null, 'Trinidad'),
('Dhalpuri roti (frozen)', 'Frozen', 'Flatbread', true, false, 8.99, null, null, 'Trinidad'),
('Sada roti', 'Staple/Bakery', 'Flatbread', true, false, 5.99, null, null, 'Trinidad'),
('Buss up shut (paratha roti), frozen', 'Frozen', 'Flatbread', true, false, 8.99, null, null, 'Trinidad'),
('Chief curry powder', 'Seasoning', 'Curry', false, true, 5.99, null, 'Chief', 'Trinidad'),
('Chief amchar masala', 'Seasoning', 'Spice blend', false, true, 5.99, null, 'Chief', 'Trinidad'),
('Green seasoning (Chief/Matouk''s)', 'Sauce/Paste', 'Marinade', false, true, 5.99, null, 'Matouk''s', 'Trinidad'),
('Matouk''s pepper sauce', 'Sauce/Paste', 'Chili', false, true, 5.99, null, 'Matouk''s', 'Trinidad'),
('Matouk''s Trinidad ketchup', 'Sauce/Paste', 'Condiment', false, true, 4.99, null, 'Matouk''s', 'Trinidad'),
('Roasted geera (cumin)', 'Seasoning', 'Spice', false, true, 5.99, null, null, 'Trinidad'),
('Split peas (channa dhal)', 'Beans/Legumes', 'Legumes', false, true, 4.99, null, null, 'Trinidad'),
('Promasa (corn flour, for coo coo)', 'Staple/Flour', 'Corn flour', false, true, 4.99, null, null, 'Trinidad'),
('Saheena (spinach fritter), frozen', 'Frozen', 'Street food', true, false, 8.99, null, null, 'Trinidad'),
('Aloo pie (frozen)', 'Frozen', 'Street food', true, false, 8.99, null, null, 'Trinidad'),
('Kuchela (mango condiment)', 'Sauce/Paste', 'Pickle', false, true, 6.99, null, null, 'Trinidad'),
('Trinidad black cake', 'Bakery', 'Cake', true, false, 24.99, null, null, 'Trinidad'),
('Pastelle (cornmeal parcel)', 'Frozen', 'Street food', true, false, 9.99, null, null, 'Trinidad'),
('Sawine / vermicelli (parched)', 'Baking', 'Vermicelli', false, true, 5.99, null, null, 'Trinidad'),
('Peardrax / apple J', 'Beverage', 'Soda', false, true, 2.99, null, 'Peardrax', 'Trinidad'),
('Solo / Chubby soft drinks', 'Beverage', 'Soda', false, true, 1.99, null, 'Solo', 'Trinidad'),
('Ponche de crème mix', 'Beverage', 'Cream liqueur', false, true, 9.99, null, null, 'Trinidad'),
('Cassareep (Real Guyana Pomeroon)', 'Sauce/Paste', 'Cassava sauce', false, true, 13.99, null, 'Real Guyana', 'Guyana'),
('Cassareep (Guyanese Pride)', 'Sauce/Paste', 'Cassava sauce', false, true, 7.99, null, 'Guyanese Pride', 'Guyana'),
('Wiri wiri pepper (fresh/sauce)', 'Produce/Sauce', 'Pepper', true, false, 6.99, null, null, 'Guyana'),
('Salara (coconut roll)', 'Bakery', 'Pastry', true, false, 9.99, null, null, 'Guyana'),
('Pine tart', 'Bakery', 'Pastry', true, false, 12.99, null, null, 'Guyana'),
('Cheese straws (wiri wiri)', 'Snacks', 'Savory snack', false, true, 11.99, null, null, 'Guyana'),
('Chico (chocolate candy)', 'Snacks', 'Confection', false, true, 4.99, null, null, 'Guyana'),
('Matterhorn mints', 'Snacks', 'Confection', false, true, 3.99, null, null, 'Guyana'),
('Demerara sugar', 'Baking', 'Sugar', false, true, 5.99, null, null, 'Guyana'),
('Metemgee ground provisions mix', 'Produce', 'Ground provision', true, false, 9.99, null, null, 'Guyana'),
('Cook-up rice mix', 'Rice', 'Rice & peas', false, true, 5.99, null, null, 'Guyana'),
('Tennis rolls', 'Bakery', 'Bread', true, false, 5.99, null, null, 'Guyana'),
('Banks Beer', 'Beverage', 'Beer (alcohol)', false, true, 3.49, null, 'Banks', 'Guyana'),
('I-Cee soft drink', 'Beverage', 'Soda', false, true, 2.49, null, 'I-Cee', 'Guyana'),
('Epis (green seasoning base)', 'Sauce/Paste', 'Marinade', true, false, 6.99, null, null, 'Haiti'),
('Pikliz (spicy pickled slaw)', 'Sauce/Paste', 'Pickle', true, false, 11.99, null, null, 'Haiti'),
('Djon djon (dried black mushroom)', 'Soup Ingredient', 'Mushroom', false, true, 16.99, null, null, 'Haiti'),
('Maggi Djon Djon (cubes/liquid)', 'Seasoning', 'Bouillon', false, true, 9.99, null, 'Maggi', 'Haiti'),
('Manba / Mamba (spicy peanut butter)', 'Sauce/Paste', 'Peanut', false, true, 9.99, null, null, 'Haiti'),
('Cremas / Kremas (coconut cream liqueur)', 'Beverage', 'Cream liqueur', false, true, 22.99, null, null, 'Haiti'),
('Dous makòs (layered milk fudge)', 'Snacks', 'Confection', false, true, 12.99, null, null, 'Haiti'),
('Kasav / Cassava bread (Haitian)', 'Staple/Bakery', 'Flatbread', true, false, 6.99, null, null, 'Haiti'),
('Tablèt pistach (peanut brittle)', 'Snacks', 'Confection', false, true, 6.99, null, null, 'Haiti'),
('Tablèt kokoye (coconut tablet)', 'Snacks', 'Confection', false, true, 6.99, null, null, 'Haiti'),
('Konfiti (fruit preserve)', 'Spread', 'Jam', false, true, 9.99, null, null, 'Haiti'),
('Rapadou (raw cane sugar block)', 'Baking', 'Sugar', false, true, 9.99, null, null, 'Haiti'),
('AK-100 / Akasan (corn drink mix)', 'Beverage', 'Corn drink', false, true, 6.99, null, null, 'Haiti'),
('Komparèt (spiced cassava-coconut cake)', 'Bakery', 'Cake', true, false, 9.99, null, null, 'Haiti'),
('Tritri (dried baby shrimp)', 'Fish/Seafood', 'Dried seafood', false, true, 6.99, null, null, 'Haiti'),
('Andui / Haitian pork seasoning', 'Seasoning', 'Marinade', false, true, 6.99, null, null, 'Haiti'),
('Amidon (starch, for labouyi)', 'Baking', 'Starch', false, true, 6.99, null, null, 'Haiti'),
('Bongu corn flakes', 'Breakfast', 'Cereal', false, true, 8.99, null, 'Bongu', 'Haiti'),
('Mayi moulen (cornmeal)', 'Staple/Flour', 'Cornmeal', false, true, 5.99, null, null, 'Haiti'),
('Pwa (beans, for diri ak pwa)', 'Beans/Legumes', 'Beans', false, true, 6.99, null, null, 'Haiti'),
('Cassava / kasav dous (sweet)', 'Snacks/Bakery', 'Cassava', true, false, 7.99, null, null, 'Haiti'),
('Boul chokola (cocoa balls)', 'Beverage', 'Cocoa', false, true, 12.99, null, null, 'Haiti'),
('Haitian coffee (Rebo/Selecto)', 'Beverage', 'Coffee', false, true, 12.99, null, 'Selecto', 'Haiti'),
('Aunt May''s Bajan pepper sauce', 'Sauce/Paste', 'Chili', false, true, 8.99, null, 'Aunt May''s', 'Barbados'),
('Aunt May''s green seasoning', 'Sauce/Paste', 'Marinade', false, true, 8.75, null, 'Aunt May''s', 'Barbados'),
('Bajan seasoning (herb wet rub)', 'Sauce/Paste', 'Marinade', true, false, 7.99, null, null, 'Barbados'),
('Cou-cou / fungee cornmeal (+ okra)', 'Staple/Flour', 'Cornmeal', false, true, 6.99, null, null, 'Barbados'),
('Fishcakes (saltfish), frozen', 'Frozen', 'Street food', true, false, 9.99, null, null, 'Barbados'),
('Conkies (cornmeal-coconut)', 'Snacks', 'Dessert', true, false, 9.99, null, null, 'Barbados'),
('Eclipse mints', 'Snacks', 'Confection', false, true, 2.99, null, 'Eclipse', 'Barbados'),
('Mauby syrup / bark', 'Beverage', 'Herbal', false, true, 6.99, null, null, 'Barbados'),
('Guava cheese / jam', 'Spread', 'Jam', false, true, 7.99, null, null, 'Barbados'),
('Grenadian cocoa balls (cocoa tea)', 'Beverage', 'Cocoa', false, true, 16.99, null, null, 'Grenada'),
('Whole nutmeg (Pure Grenada)', 'Seasoning', 'Spice', false, true, 9.99, null, null, 'Grenada'),
('Mace (Grenadian)', 'Seasoning', 'Spice', false, true, 10.99, null, null, 'Grenada'),
('De La Grenade nutmeg jam', 'Spread', 'Jam', false, true, 9.99, null, null, 'Grenada'),
('Bois bandé (bark)', 'Beverage/Wellness', 'Tonic bark', false, true, 10.99, null, null, 'Grenada'),
('Cassava farine', 'Staple/Flour', 'Cassava', false, true, 7.99, null, null, 'Grenada'),
('Cocoa sticks / cocoa tea (St. Lucia)', 'Beverage', 'Cocoa', false, true, 14.99, null, null, 'St. Lucia'),
('Sea moss (St. Lucian, dried)', 'Superfood', 'Sea moss', false, true, 24.99, null, null, 'St. Lucia'),
('Sea moss gel', 'Superfood', 'Sea moss', true, false, 22.99, null, null, 'St. Lucia'),
('Green fig (green banana)', 'Produce', 'Banana', true, false, 4.99, null, null, 'St. Lucia'),
('Callaloo (dasheen leaf), fresh/canned', 'Produce', 'Greens', true, false, 5.99, null, null, 'St. Lucia'),
('Ground provisions (dasheen/eddoe/yam)', 'Produce', 'Ground provision', true, false, 4.99, null, null, 'Eastern Caribbean'),
('Cocoa balls w/ cinnamon (Dominica)', 'Beverage', 'Cocoa', false, true, 12.99, null, null, 'Dominica'),
('Bahamian conch (frozen)', 'Frozen', 'Seafood', true, false, 19.99, null, null, 'Bahamas'),
('Goombay punch soda', 'Beverage', 'Soda', false, true, 2.49, null, null, 'Bahamas'),
('Belizean recado (annatto paste)', 'Sauce/Paste', 'Spice paste', false, true, 5.99, null, null, 'Belize'),
('Marie Sharp''s hot sauce', 'Sauce/Paste', 'Chili', false, true, 6.99, null, 'Marie Sharp''s', 'Belize'),
('Fernandes soft drink (various)', 'Beverage', 'Soda', false, true, 3.49, null, 'Fernandes', 'Suriname'),
('Pom / pomtajer (grated taro), frozen', 'Frozen', 'Casserole base', true, false, 12.99, null, null, 'Suriname'),
('Roti mix / masala (Paloeloe)', 'Seasoning/Flour', 'Roti mix', false, true, 7.99, null, null, 'Suriname'),
('Bara (fried dhal ring)', 'Snacks', 'Street food', true, false, 6.99, null, null, 'Suriname'),
('Telo (fried cassava & saltfish)', 'Snacks', 'Street food', true, false, 9.99, null, null, 'Suriname'),
('Ketjap manis (sweet soy)', 'Sauce/Paste', 'Soy sauce', false, true, 6.99, null, null, 'Suriname'),
('Trassi (fermented shrimp paste)', 'Sauce/Paste', 'Shrimp paste', false, true, 6.99, null, null, 'Suriname'),
('Parbo beer', 'Beverage', 'Beer (alcohol)', false, true, 3.49, null, 'Parbo', 'Suriname'),
('Sazón / Sofrito (Goya)', 'Seasoning', 'Spice blend', false, true, 4.99, null, 'Goya', 'Dominican Republic'),
('Casabe (cassava bread)', 'Staple/Bakery', 'Flatbread', false, true, 6.99, null, null, 'Dominican Republic'),
('Mangú (green plantain) mix', 'Staple', 'Plantain', true, false, 5.99, null, null, 'Dominican Republic'),
('Morir soñando drink mix', 'Beverage', 'Milk/orange', false, true, 4.99, null, null, 'Dominican Republic'),
('Stockfish (okporoko), whole', 'Fish/Seafood', 'Dried fish', false, true, 24.99, null, null, 'Nigeria'),
('Stockfish heads/bits', 'Fish/Seafood', 'Dried fish', false, true, 14.99, null, null, 'West Africa'),
('Panla (smoked whiting/hake)', 'Fish/Seafood', 'Smoked fish', false, true, 12.99, null, null, 'Nigeria'),
('Bonga fish (smoked), whole', 'Fish/Seafood', 'Smoked fish', false, true, 12.99, null, null, 'West Africa'),
('Peeled bonga (agbodo)', 'Fish/Seafood', 'Smoked fish', false, true, 10.99, null, null, 'West Africa'),
('Smoked catfish (eja aro)', 'Fish/Seafood', 'Smoked fish', false, true, 15.99, null, null, 'Nigeria'),
('Smoked mackerel (titus)', 'Fish/Seafood', 'Smoked fish', false, true, 12.99, null, null, 'West Africa'),
('Asa / eja osan (smoked knife fish)', 'Fish/Seafood', 'Smoked fish', false, true, 13.99, null, null, 'Nigeria'),
('Dried prawns/shrimp (jumbo)', 'Fish/Seafood', 'Dried seafood', false, true, 12.99, null, null, 'West Africa'),
('Whole crayfish (ungrinded)', 'Fish/Seafood', 'Dried seafood', false, true, 11.99, null, null, 'West Africa'),
('Koobi (salted tilapia, Ghana)', 'Fish/Seafood', 'Salted fish', false, true, 11.99, null, null, 'Ghana'),
('Momone (fermented fish, Ghana)', 'Fish/Seafood', 'Fermented fish', false, true, 10.99, null, null, 'Ghana'),
('Salted pigtail', 'Meat', 'Salted meat', true, false, 9.99, null, null, 'Caribbean'),
('Salted mackerel', 'Fish/Seafood', 'Salted fish', false, true, 11.99, null, null, 'Caribbean'),
('Smoked herring', 'Fish/Seafood', 'Smoked fish', false, true, 6.99, null, null, 'Caribbean'),
('Salted oxtail (per lb)', 'Meat', 'Salted meat', true, false, 12.99, null, null, 'Caribbean'),
('Salted cod (bacalao)', 'Fish/Seafood', 'Salted fish', false, true, 15.99, null, null, 'Caribbean'),
('African yam (puna, approx 3 lb)', 'Produce', 'Tuber', true, false, 15.99, null, null, 'Nigeria'),
('Yellow yam (400g)', 'Produce', 'Tuber', true, false, 8.99, null, null, 'Jamaica'),
('Cocoyam / taro (dasheen)', 'Produce', 'Tuber', true, false, 4.99, null, null, 'West Africa'),
('Cassava / yuca (fresh)', 'Produce', 'Tuber', true, false, 3.99, null, null, 'Pan-tropical'),
('Green plantain (each)', 'Produce', 'Plantain', true, false, 1.99, null, null, 'Pan-tropical'),
('Ripe plantain (each)', 'Produce', 'Plantain', true, false, 1.99, null, null, 'Pan-tropical'),
('Green cooking banana (per lb)', 'Produce', 'Banana', true, false, 0.89, null, null, 'Caribbean'),
('Jamaican green banana (each)', 'Produce', 'Banana', true, false, 1.29, null, null, 'Jamaica'),
('Scotch bonnet peppers (pack)', 'Produce', 'Pepper', true, false, 4.99, null, null, 'Caribbean'),
('Callaloo (chopped, ~400g)', 'Produce', 'Greens', true, false, 8.99, null, null, 'Jamaica'),
('Ackee (fresh, seasonal)', 'Produce', 'Fruit', true, false, 9.99, null, null, 'Jamaica'),
('Breadfruit (each)', 'Produce', 'Starch fruit', true, false, 6.99, null, null, 'Caribbean'),
('Bitter melon (caraili)', 'Produce', 'Vegetable', true, false, 3.99, null, null, 'Caribbean'),
('Dasheen bush (taro leaf)', 'Produce', 'Greens', true, false, 4.99, null, null, 'Caribbean'),
('Sorrel (fresh, seasonal)', 'Produce', 'Herbal', true, false, 5.99, null, null, 'Caribbean'),
('Garden egg (African eggplant)', 'Produce', 'Vegetable', true, false, 4.99, null, null, 'West Africa'),
('Okra (fresh, 500g)', 'Produce', 'Vegetable', true, false, 4.99, null, null, 'Pan-tropical'),
('Frozen ewedu (jute leaves)', 'Frozen', 'Greens', true, false, 6.99, null, null, 'Nigeria'),
('Frozen banana leaves', 'Frozen', 'Wrapping', true, false, 4.99, null, null, 'Pan-tropical'),
('Frozen soursop pulp', 'Frozen', 'Fruit', true, false, 6.99, null, null, 'Caribbean'),
('Frozen cassava leaf', 'Frozen', 'Greens', true, false, 8.99, null, null, 'Central Africa'),
('Uziza / utazi (fresh bunch)', 'Produce', 'Greens', true, false, 5.99, null, null, 'Nigeria'),
('Waterleaf (gbure)', 'Produce', 'Greens', true, false, 4.99, null, null, 'West Africa'),
('Ugu (fluted pumpkin), fresh', 'Produce', 'Greens', true, false, 5.99, null, null, 'Nigeria'),
('Tigernut (fresh/dried)', 'Produce/Superfood', 'Tuber', false, true, 8.99, null, null, 'West Africa'),
('Dudu-Osun African black soap', 'Household/Beauty', 'Soap', false, true, 4.99, null, 'Dudu-Osun', 'Nigeria'),
('Raw African black soap (Ghana)', 'Household/Beauty', 'Soap', false, true, 6.99, null, null, 'Ghana'),
('Raw unrefined shea butter (ori)', 'Household/Beauty', 'Skincare', false, true, 9.99, null, null, 'West Africa'),
('Shea butter oil (Aweni)', 'Household/Beauty', 'Skincare', false, true, 8.99, null, null, 'Nigeria'),
('Cocoa butter (raw)', 'Household/Beauty', 'Skincare', false, true, 7.99, null, null, 'West Africa'),
('Black Jamaican castor oil', 'Household/Beauty', 'Haircare', false, true, 9.99, null, null, 'Jamaica'),
('Coconut oil (cold-pressed)', 'Cooking Oil/Beauty', 'Oil', false, true, 8.99, null, null, 'Pan-tropical'),
('Chewing stick (pako/orin)', 'Household', 'Oral care', false, true, 3.99, null, null, 'West Africa'),
('African bath sponge (sapo/net)', 'Household', 'Bath', false, true, 3.99, null, null, 'West Africa'),
('Camwood powder (osun)', 'Household/Beauty', 'Skincare', false, true, 6.99, null, null, 'Nigeria'),
('Ose dudu / anago soap', 'Household/Beauty', 'Soap', false, true, 5.99, null, null, 'Nigeria'),
('Incense sticks / etan (frankincense)', 'Household', 'Incense', false, true, 5.99, null, null, 'East Africa'),
('Dutch pot (aluminium, small)', 'Household', 'Cookware', false, true, 24.99, null, null, 'Caribbean'),
('Coal pot / stovetop', 'Household', 'Cookware', false, true, 34.99, null, null, 'Caribbean'),
('Rice strainer (plastic)', 'Household', 'Kitchen tool', false, true, 4, null, null, 'Pan-African'),
('Mortar & pestle (wooden, odo/mwiko)', 'Household', 'Kitchen tool', false, true, 29.99, null, null, 'Pan-African'),
('Jebena (Ethiopian coffee pot)', 'Household', 'Kitchen tool', false, true, 24.99, null, null, 'Ethiopia'),
('Fufu pounder / masher', 'Household', 'Kitchen tool', false, true, 19.99, null, null, 'West Africa'),
('Mitad / injera griddle', 'Household', 'Kitchen tool', false, true, 79.99, null, null, 'Ethiopia'),
('Potjie pot (cast iron)', 'Household', 'Cookware', false, true, 59.99, null, null, 'South Africa'),
('Calabash bowl', 'Household', 'Serveware', false, true, 12.99, null, null, 'Pan-African'),
('Grater (cassava/coconut)', 'Household', 'Kitchen tool', false, true, 9.99, null, null, 'Caribbean'),
('Indomie instant noodles (chicken)', 'Noodles', 'Instant', false, true, 6.99, null, 'Indomie', 'Nigeria'),
('Indomie (onion/pepper soup)', 'Noodles', 'Instant', false, true, 6.99, null, 'Indomie', 'Nigeria'),
('Golden Penny spaghetti', 'Pasta', 'Dry pasta', false, true, 3.49, null, 'Golden Penny', 'Nigeria'),
('Bella / Ekono spaghetti', 'Pasta', 'Dry pasta', false, true, 1.99, null, null, 'Zimbabwe'),
('Macaroni (3kg, for macaroni pie)', 'Pasta', 'Dry pasta', false, true, 6.99, null, null, 'Caribbean'),
('Ovaltine / Cerelac baby cereal', 'Breakfast', 'Cereal', false, true, 9.99, null, 'Ovaltine', 'Pan-African'),
('Custard powder (Bird''s/Checkers)', 'Baking', 'Dessert', false, true, 4.99, null, null, 'Pan-African'),
('Cornmeal porridge mix', 'Breakfast', 'Porridge', false, true, 5.99, null, null, 'Caribbean'),
('Peanut porridge mix', 'Breakfast', 'Porridge', false, true, 5.99, null, null, 'Jamaica'),
('Hominy corn (canned)', 'Breakfast', 'Corn', false, true, 3.49, null, null, 'Caribbean'),
('Cream of wheat', 'Breakfast', 'Porridge', false, true, 5.99, null, null, 'Caribbean'),
('Oat flour (swallow)', 'Baking', 'Flour', false, true, 8.99, null, null, 'Nigeria'),
('Poundo potato (swallow)', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Nigeria'),
('Mixed grain swallow', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Nigeria'),
('Tigernut fufu (low-carb swallow)', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Nigeria'),
('Eggplant fufu (low-carb)', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Nigeria'),
('Cabbage fufu (low-carb)', 'Staple/Flour', 'Swallow', false, true, 9.99, null, null, 'Nigeria'),
('Baking powder / bicarbonate (for hardo/festival)', 'Baking', 'Leavening', false, true, 3.49, null, null, 'Pan-Caribbean'),
('Coconut milk (canned, Grace/Chef)', 'Baking', 'Coconut', false, true, 2.99, null, 'Grace', 'Caribbean'),
('Evaporated milk (Carnation)', 'Dairy', 'Milk', false, true, 2.99, null, 'Carnation', 'Pan-Caribbean'),
('Condensed milk (sweetened)', 'Dairy', 'Milk', false, true, 3.49, null, null, 'Pan-Caribbean'),
('Vanilla / mixed essence', 'Baking', 'Flavoring', false, true, 4.99, null, null, 'Caribbean'),
('Grace Parboiled Basmati Rice 10lb', 'Rice & Grains', 'Basmati', false, true, 24.99, null, 'Grace', 'Jamaica'),
('Grace Long Grain Parboiled Rice 2kg', 'Rice & Grains', 'Parboiled', false, true, 8.5, null, 'Grace', 'Jamaica'),
('Grace White Rice 2kg', 'Rice & Grains', 'White long grain', false, true, 6.99, null, 'Grace', 'Jamaica'),
('Tilda Pure Original Basmati Rice 907g', 'Rice & Grains', 'Basmati', false, true, 7.49, null, 'Tilda', 'Grenada'),
('Rooster Scented Jasmine Rice 8kg', 'Rice & Grains', 'Jasmine', false, true, 21.99, null, 'Rooster', null),
('Rooster Extra Fancy Long Grain 8kg', 'Rice & Grains', 'Long grain', false, true, 19.99, null, 'Rooster', null),
('Abakaliki Rice (Organic Nigerian)', 'Rice & Grains', 'Nigerian local', false, true, 13, null, 'Abakaliki', 'Nigeria'),
('Ofada Rice (Nigerian brown)', 'Rice & Grains', 'Nigerian local', false, true, 20, null, null, 'Nigeria'),
('Par Excellence Rice 10lb', 'Rice & Grains', 'Parboiled', false, true, 22.99, null, 'Par Excellence', 'Nigeria'),
('Maharani Diabetic Rice 10lb', 'Rice & Grains', 'Specialty', false, true, 24.99, null, 'Maharani', null),
('Golden Penny Semolina 1kg', 'Rice & Grains', 'Semolina', false, true, 7.99, null, 'Golden Penny', 'Nigeria'),
('Fatou Attieke (cassava couscous) sachet', 'Rice & Grains', 'Cassava couscous', false, true, 8, null, null, 'Ivory Coast'),
('Yolélé Fonio', 'Rice & Grains', 'Ancient grain', false, true, 11.99, null, 'Yolélé', 'Senegal'),
('Teff Grain/Flour White 2lb', 'Rice & Grains', 'Teff', false, true, 14.99, null, null, 'Ethiopia'),
('Teff Flour Brown 5lb', 'Rice & Grains', 'Teff', false, true, 34.99, null, null, 'Ethiopia'),
('Chief Ground Rice 200g', 'Rice & Grains', 'Ground rice', false, true, 3.49, null, 'Chief', 'Trinidad'),
('Tapioca/Cassava Pearls', 'Rice & Grains', 'Tapioca', false, true, 5.99, null, null, 'Nigeria'),
('White Garri (Ijebu) 4lb', 'Flours & Swallows', 'Garri', false, true, 9, null, null, 'Nigeria'),
('Yellow Garri 4lb', 'Flours & Swallows', 'Garri', false, true, 9, null, null, 'Nigeria'),
('Yam Flour (Elubo)', 'Flours & Swallows', 'Yam flour', false, true, 15.99, null, null, 'Nigeria'),
('Fermented Cassava Flour (Lafun) 4lb', 'Flours & Swallows', 'Cassava flour', false, true, 10, null, null, 'Nigeria'),
('Ayoola Poundo Yam Flour', 'Flours & Swallows', 'Pounded yam', false, true, 14.99, null, 'Ayoola', 'Nigeria'),
('Iyah Ado Pounded Yam (Iyan)', 'Flours & Swallows', 'Pounded yam', false, true, 10.99, null, 'Iyah Ado', 'Nigeria'),
('Tropiway Plantain Fufu Flour', 'Flours & Swallows', 'Plantain fufu', false, true, 9.99, null, 'Tropiway', 'Nigeria'),
('Ayoola Plantain Flour', 'Flours & Swallows', 'Plantain flour', false, true, 12.99, null, 'Ayoola', 'Nigeria'),
('Bambara Flour (Okpa)', 'Flours & Swallows', 'Bean flour', false, true, 15, null, null, 'Nigeria'),
('Ayoola Rice Flour 2lb', 'Flours & Swallows', 'Rice flour', false, true, 5, null, 'Ayoola', 'Nigeria'),
('Motherland''s Beans Flour 1kg', 'Flours & Swallows', 'Bean flour', false, true, 6.99, null, 'Motherland''s', 'Nigeria'),
('Cocoyam Flour', 'Flours & Swallows', 'Cocoyam', false, true, 9.99, null, null, null),
('Oat Flour (ScotMaple)', 'Flours & Swallows', 'Oat flour', false, true, 9, null, null, null),
('Banku Mix', 'Flours & Swallows', 'Ghanaian swallow', false, true, 8.99, null, null, 'Ghana'),
('Kenkey (Ghanaian)', 'Flours & Swallows', 'Ghanaian swallow', false, true, 6.99, null, null, 'Ghana'),
('Cassava Fufu Flour (Tropiway)', 'Flours & Swallows', 'Cassava fufu', false, true, 8.99, null, 'Tropiway', 'Nigeria'),
('Eggplant Fufu (low-carb) 1lb', 'Flours & Swallows', 'Low-carb swallow', false, true, 12.99, null, null, 'West Africa'),
('Tigernut Fufu 520g', 'Flours & Swallows', 'Low-carb swallow', false, true, 12.99, null, null, 'West Africa'),
('Poundo Potato', 'Flours & Swallows', 'Potato swallow', false, true, 11.99, null, null, 'Nigeria'),
('Wheat Flour (swallow)', 'Flours & Swallows', 'Wheat swallow', false, true, 9.99, null, null, 'West Africa'),
('Black Eyed Peas (Beans) 4lb', 'Beans & Legumes', 'Black-eyed peas', false, true, 11, null, null, 'Nigeria'),
('Honey (Oloyin) Beans 4lb', 'Beans & Legumes', 'Brown beans', false, true, 13, null, null, 'Nigeria'),
('Drum Beans (Nigerian brown) 4lb', 'Beans & Legumes', 'Brown beans', false, true, 11, null, null, 'Nigeria'),
('Peeled Beans (Davisol)', 'Beans & Legumes', 'Peeled beans', false, true, 9, null, null, 'West Africa'),
('Grace Red Kidney Beans (canned) 398ml', 'Beans & Legumes', 'Canned beans', false, true, 1.99, null, 'Grace', 'Jamaica'),
('Grace Gungo (Pigeon) Peas canned', 'Beans & Legumes', 'Canned peas', false, true, 2.29, null, 'Grace', 'Jamaica'),
('Grace Chick Peas canned', 'Beans & Legumes', 'Canned beans', false, true, 1.99, null, 'Grace', 'Jamaica'),
('Grace Butter Beans canned', 'Beans & Legumes', 'Canned beans', false, true, 2.29, null, 'Grace', 'Jamaica'),
('Maywah Yellow Peas Flour 28oz', 'Beans & Legumes', 'Split pea flour', false, true, 4.99, null, null, 'Trinidad'),
('Dry Red Kidney Beans 2lb', 'Beans & Legumes', 'Dry beans', false, true, 4.99, null, null, null),
('Dry Pigeon (Gungo) Peas 2lb', 'Beans & Legumes', 'Dry peas', false, true, 4.99, null, null, 'Jamaica'),
('Brown/Red Lentils 2lb', 'Beans & Legumes', 'Lentils', false, true, 4.99, null, null, null),
('Yellow Split Peas 2lb', 'Beans & Legumes', 'Split peas', false, true, 3.99, null, null, 'Trinidad'),
('Soya Chunks', 'Beans & Legumes', 'Soya', false, true, 3.49, null, null, 'Cameroon'),
('Grace Ackee in Salt Water 19oz', 'Canned & Jarred', 'Ackee', false, true, 15.99, null, 'Grace', 'Jamaica'),
('JCS Ackees in Brine 19oz', 'Canned & Jarred', 'Ackee', false, true, 16.99, null, 'JCS', 'Jamaica'),
('Spur Tree Ackee 19oz', 'Canned & Jarred', 'Ackee', false, true, 11.49, null, 'Spur Tree', 'Jamaica'),
('Linstead Market Ackee 19oz', 'Canned & Jarred', 'Ackee', false, true, 14.99, null, 'Linstead Market', 'Jamaica'),
('Carib Ackee in Brine 19oz', 'Canned & Jarred', 'Ackee', false, true, 13.99, null, 'Carib', 'Jamaica'),
('Grace Callaloo 1.1lb', 'Canned & Jarred', 'Callaloo', false, true, 3.69, null, 'Grace', 'Jamaica'),
('Spur Tree Callaloo 19oz', 'Canned & Jarred', 'Callaloo', false, true, 2.79, null, 'Spur Tree', 'Jamaica'),
('Grace Coconut Milk 400ml', 'Canned & Jarred', 'Coconut milk', false, true, 1.94, null, 'Grace', 'Jamaica'),
('Grace Coconut Milk Powder 50g', 'Canned & Jarred', 'Coconut milk powder', false, true, 1.29, null, 'Grace', 'Jamaica'),
('Titus Sardines 125g', 'Canned & Jarred', 'Sardines', false, true, 2.5, null, 'Titus', 'Nigeria'),
('Geisha Mackerel 155g', 'Canned & Jarred', 'Mackerel', false, true, 2.99, null, 'Geisha', 'Nigeria'),
('Geisha Jack Mackerel 425g', 'Canned & Jarred', 'Mackerel', false, true, 5.99, null, 'Geisha', 'Nigeria'),
('African Queen Mackerel 425g', 'Canned & Jarred', 'Mackerel', false, true, 9.5, null, 'African Queen', 'Ghana'),
('Grace Mackerel in Tomato 155g', 'Canned & Jarred', 'Mackerel', false, true, 1.25, null, 'Grace', 'Jamaica'),
('Exeter Corned Beef 340g', 'Canned & Jarred', 'Corned beef', false, true, 6.99, null, 'Exeter', 'Jamaica'),
('Grace Corned Beef 340g', 'Canned & Jarred', 'Corned beef', false, true, 4.99, null, 'Grace', 'Jamaica'),
('Grace Vienna Sausage', 'Canned & Jarred', 'Canned meat', false, true, 1.99, null, 'Grace', 'Jamaica'),
('Rooster Luncheon Meat 340g', 'Canned & Jarred', 'Luncheon meat', false, true, 3.79, null, 'Rooster', null),
('Heinz Beanz Tomato 415g', 'Canned & Jarred', 'Baked beans', false, true, 3.09, null, 'Heinz', 'Ethiopia'),
('Gino/Derica Tomato Paste 400g', 'Canned & Jarred', 'Tomato paste', false, true, 2.49, null, 'Gino', 'Nigeria'),
('Tasty Tom Tomato Paste 210g', 'Canned & Jarred', 'Tomato paste', false, true, 1.99, null, 'Tasty Tom', null),
('Grace Baked Beans', 'Canned & Jarred', 'Baked beans', false, true, 2.29, null, 'Grace', 'Jamaica'),
('Grace Corn (canned)', 'Canned & Jarred', 'Canned veg', false, true, 1.99, null, 'Grace', 'Jamaica'),
('Flaked Light Tuna 170g', 'Canned & Jarred', 'Tuna', false, true, 2.49, null, null, 'Somalia'),
('Maggi Star Seasoning Cube 400g (100 cubes)', 'Seasonings', 'Bouillon cube', false, true, 12.99, null, 'Maggi', 'Nigeria'),
('Maggi Chicken Seasoning Powder', 'Seasonings', 'Bouillon powder', false, true, 16.99, null, 'Maggi', 'Nigeria'),
('Knorr Bouillon Cubes Chicken 69g', 'Seasonings', 'Bouillon cube', false, true, 2.99, null, 'Knorr', 'Nigeria'),
('Maggi Shrimp/Crevette Seasoning 600g', 'Seasonings', 'Bouillon', false, true, 15.99, null, 'Maggi', 'Nigeria'),
('Grace Jamaican Jerk Seasoning Mild 284g', 'Seasonings', 'Jerk', false, true, 4.75, null, 'Grace', 'Jamaica'),
('Walkerswood Jerk Seasoning Hot 280g', 'Seasonings', 'Jerk', false, true, 6.99, null, 'Walkerswood', 'Jamaica'),
('Betapac Curry Powder 200g', 'Seasonings', 'Curry', false, true, 5.49, null, 'Betapac', 'Jamaica'),
('Chief All Purpose Seasoning 40g', 'Seasonings', 'All purpose', false, true, 0.99, null, 'Chief', 'Trinidad'),
('Suya Pepper (Yaji) spice', 'Seasonings', 'Suya spice', false, true, 8.99, null, null, 'Nigeria'),
('Pepper Soup Spice', 'Seasonings', 'Peppersoup', false, true, 7.99, null, null, 'Nigeria'),
('Goya Sazón (culantro y achiote)', 'Seasonings', 'Latin/Caribbean', false, true, 3.99, null, 'Goya', 'Dominican Republic'),
('Goya Adobo All Purpose', 'Seasonings', 'Latin/Caribbean', false, true, 4.49, null, 'Goya', 'Dominican Republic'),
('Berbere Spice Blend', 'Seasonings', 'Ethiopian', false, true, 9.99, null, null, 'Ethiopia'),
('Berbere Almi 1kg', 'Seasonings', 'Ethiopian', false, true, 26.99, null, 'Almi', 'Ethiopia'),
('Mitmita Spice Blend', 'Seasonings', 'Ethiopian', false, true, 9.99, null, null, 'Ethiopia'),
('Shiro Powder', 'Seasonings', 'Ethiopian', false, true, 12.99, null, null, 'Ethiopia'),
('Xawaash Somali Spice 120g', 'Seasonings', 'Somali', false, true, 9.99, null, null, 'Somalia'),
('Korarima (Ethiopian cardamom) ground', 'Seasonings', 'Ethiopian', false, true, 11.99, null, null, 'Ethiopia'),
('Ground Crayfish 100g', 'Seasonings', 'Dried crayfish', false, true, 9.99, null, null, 'Nigeria'),
('Locust Beans (Iru/Dawadawa) 100g', 'Seasonings', 'Fermented condiment', false, true, 9, null, null, 'Nigeria'),
('Cameroon Pepper ground', 'Seasonings', 'Chili', false, true, 7.99, null, null, 'Cameroon'),
('Ehuru / Uziza Seeds', 'Seasonings', 'Soup spice', false, true, 8.99, null, null, 'Nigeria'),
('Grace Green Seasoning 10oz', 'Sauces & Condiments', 'Green seasoning', false, true, 4.89, null, 'Grace', 'Jamaica'),
('Walkerswood Green Seasoning 10oz', 'Sauces & Condiments', 'Green seasoning', false, true, 4.59, null, 'Walkerswood', 'Jamaica'),
('Mabel''s Green Seasoning 10oz', 'Sauces & Condiments', 'Green seasoning', false, true, 1.99, null, null, 'Jamaica'),
('Grace Hot Pepper Sauce 12oz', 'Sauces & Condiments', 'Pepper sauce', false, true, 3.59, null, 'Grace', 'Jamaica'),
('Grace Browning 4.8oz', 'Sauces & Condiments', 'Browning', false, true, 3.49, null, 'Grace', 'Jamaica'),
('Walkerswood Jerk Marinade', 'Sauces & Condiments', 'Jerk marinade', false, true, 6.49, null, 'Walkerswood', 'Jamaica'),
('Guyana Tasty Scotch Bonnet Sauce 300ml', 'Sauces & Condiments', 'Pepper sauce', false, true, 6.69, null, 'Guyana Tasty', 'Guyana'),
('Real Guyana Cassareep 13oz', 'Sauces & Condiments', 'Cassareep', false, true, 6.29, null, 'Real Guyana', 'Guyana'),
('Shito (Ghanaian pepper sauce)', 'Sauces & Condiments', 'Pepper sauce', false, true, 8.99, null, null, 'Ghana'),
('Nina Red Palm Oil 1L', 'Sauces & Condiments', 'Palm oil', false, true, 16.99, null, 'Nina', 'Nigeria'),
('Groundnut/Peanut Paste', 'Sauces & Condiments', 'Peanut paste', false, true, 6.99, null, null, null),
('Sauce So Good (pepper mix)', 'Sauces & Condiments', 'Stew base', false, true, 12.99, null, null, 'Nigeria'),
('Nerrido/Ofada Stew', 'Sauces & Condiments', 'Stew', false, true, 13.99, null, null, 'Nigeria'),
('Heinz Salad Cream', 'Sauces & Condiments', 'Condiment', false, true, 4.99, null, 'Heinz', 'Nigeria'),
('Basbaas Somali Hot Sauce', 'Sauces & Condiments', 'Hot sauce', false, true, 11.99, null, 'Basbaas', 'Somalia'),
('Grace Tomato Ketchup', 'Sauces & Condiments', 'Ketchup', false, true, 2.99, null, 'Grace', 'Jamaica'),
('Praise Zomi Palm Oil 1L', 'Oils & Fats', 'Palm oil (zomi)', false, true, 14.99, null, 'Praise Zomi', 'Nigeria'),
('Omni Red Palm Oil 500ml', 'Oils & Fats', 'Palm oil', false, true, 8.99, null, 'Omni', null),
('Nature''s Best Ngopa Palm Oil 1L', 'Oils & Fats', 'Palm oil', false, true, 12.99, null, 'Nature''s Best', null),
('Ofada Palm Oil (bleached)', 'Oils & Fats', 'Bleached palm oil', false, true, 21, null, null, 'Nigeria'),
('Africa''s Best Palm Kernel Oil 1L', 'Oils & Fats', 'Palm kernel oil', false, true, 13.99, null, 'Africa''s Best', null),
('Groundnut (Peanut) Oil 2L', 'Oils & Fats', 'Groundnut oil', false, true, 14.99, null, null, null),
('Coconut Oil (Mychopchop)', 'Oils & Fats', 'Coconut oil', false, true, 12.99, null, null, null),
('Goya Vegetable Oil 24oz', 'Oils & Fats', 'Vegetable oil', false, true, 3.99, null, 'Goya', 'Dominican Republic'),
('Shea Butter (cooking, Aweni)', 'Oils & Fats', 'Shea butter', false, true, 9.99, null, null, 'Nigeria'),
('Fresh/Frozen Oxtail per lb', 'Frozen', 'Meat', true, false, 13.99, null, null, 'Caribbean'),
('Goat Meat with Skin (frozen)', 'Frozen', 'Meat', true, false, 31, null, null, 'Nigeria'),
('Cow Skin (Ponmo)', 'Frozen', 'Meat', true, false, 18.99, null, null, 'Nigeria'),
('Beef Tripe (Saki)', 'Frozen', 'Meat', true, false, 6.99, null, null, 'Nigeria'),
('Smoked Turkey 2lb', 'Frozen', 'Meat', true, false, 19.99, null, null, null),
('Frozen Croaker/Mackerel Fish per lb', 'Frozen', 'Fish', true, false, 6.99, null, null, null),
('Frozen Tilapia whole', 'Frozen', 'Fish', true, false, 8.99, null, null, 'Ghana'),
('Frozen Spinach (soup)', 'Frozen', 'Vegetables', true, false, 4.99, null, null, null),
('Ewedu (jute leaves, frozen)', 'Frozen', 'Vegetables', true, false, 4.99, null, null, 'Nigeria'),
('Frozen Banana Leaves', 'Frozen', 'Vegetables', true, false, 4.99, null, null, null),
('Frozen Ripe Plantain', 'Frozen', 'Vegetables', true, false, 4.49, null, null, 'Pan-tropical'),
('Frozen Grated Cassava', 'Frozen', 'Vegetables', true, false, 5.99, null, null, null),
('Caribbean Food Delights Beef Patties (frozen) 10oz', 'Frozen', 'Patties', true, false, 4.99, null, 'Carib', 'Jamaica'),
('Frozen Roti Skins (paratha)', 'Frozen', 'Dough/roti', true, false, 6.99, null, null, 'Trinidad'),
('Frozen Ackee', 'Frozen', 'Vegetables', true, false, 12.99, null, null, 'Jamaica'),
('Frozen Breadfruit', 'Frozen', 'Vegetables', true, false, 7.99, null, null, 'Caribbean'),
('Peak Powdered Milk 400g', 'Dairy & Milk', 'Powdered milk', false, true, 19.99, null, 'Peak', 'Nigeria'),
('Peak Powdered Milk 900g', 'Dairy & Milk', 'Powdered milk', false, true, 35.99, null, 'Peak', 'Nigeria'),
('Nido Dry Whole Milk 900g', 'Dairy & Milk', 'Powdered milk', false, true, 27.99, null, 'Nido', 'Nigeria'),
('Nido Fortificada 400g', 'Dairy & Milk', 'Powdered milk', false, true, 14.99, null, 'Nido', 'Nigeria'),
('Carnation Evaporated Milk 354ml', 'Dairy & Milk', 'Evaporated milk', false, true, 2.79, null, 'Carnation', 'Caribbean'),
('Grace Evaporated Milk', 'Dairy & Milk', 'Evaporated milk', false, true, 2.29, null, 'Grace', 'Jamaica'),
('Eagle Brand Condensed Milk 300ml', 'Dairy & Milk', 'Condensed milk', false, true, 3.97, null, null, 'Pan-Caribbean'),
('Grace Sweetened Condensed Milk', 'Dairy & Milk', 'Condensed milk', false, true, 3.49, null, 'Grace', 'Jamaica'),
('Cowbell Powdered Milk sachet', 'Dairy & Milk', 'Powdered milk', false, true, 1.49, null, 'Cowbell', 'Nigeria'),
('Imperial Butter', 'Dairy & Milk', 'Butter', true, false, 5.99, null, null, null),
('Nestlé Golden Morn 900g', 'Cereals & Breakfast', 'Maize cereal', false, true, 11.99, null, 'Golden Morn', 'Nigeria'),
('Nestlé Cerelac Wheat & Milk 400g', 'Cereals & Breakfast', 'Infant cereal', false, true, 14.99, null, 'Cerelac', 'Pan-African'),
('Nestlé Cerelac Maize 1kg', 'Cereals & Breakfast', 'Infant cereal', false, true, 25.99, null, 'Cerelac', 'Pan-African'),
('Ogi/Pap (fermented corn)', 'Cereals & Breakfast', 'Corn pap', true, false, 6.99, null, null, null),
('Grace Instant Cornmeal Porridge', 'Cereals & Breakfast', 'Porridge', false, true, 3.99, null, 'Grace', 'Jamaica'),
('Grace Hominy Corn', 'Cereals & Breakfast', 'Porridge', false, true, 3.49, null, 'Grace', 'Jamaica'),
('Cream of Wheat', 'Cereals & Breakfast', 'Porridge', false, true, 5.99, null, null, null),
('Quaker Quick Oats 1kg', 'Cereals & Breakfast', 'Oats', false, true, 3.97, null, 'Quaker', null),
('Lasco Food Drink (porridge mix)', 'Cereals & Breakfast', 'Drink mix', false, true, 4.99, null, null, null),
('Beso (roasted barley flour)', 'Cereals & Breakfast', 'Ethiopian', false, true, 15.99, null, null, 'Ethiopia'),
('Custard Powder (Checkers)', 'Cereals & Breakfast', 'Custard', false, true, 4.99, null, null, 'Pan-African'),
('Grace Plantain Chips 85g', 'Snacks', 'Plantain chips', false, true, 1.69, null, 'Grace', 'Jamaica'),
('Go Chips Plantain Chips', 'Snacks', 'Plantain chips', false, true, 2.99, null, 'Go Chips', null),
('Olu Olu Plantain Chips', 'Snacks', 'Plantain chips', false, true, 2.99, null, 'Olu Olu', null),
('Feldos Chin Chin', 'Snacks', 'Chin chin', false, true, 5.99, null, 'Feldos', 'Nigeria'),
('Cornstick (Kokoro)', 'Snacks', 'Corn snack', false, true, 2.99, null, null, 'Nigeria'),
('Kuli-Kuli (peanut snack)', 'Snacks', 'Peanut snack', false, true, 6.99, null, null, null),
('Large Peanuts (Epa)', 'Snacks', 'Nuts', false, true, 5.99, null, null, 'Nigeria'),
('Excelsior Water Crackers', 'Snacks', 'Crackers', false, true, 3.99, null, 'Excelsior', 'Jamaica'),
('Crix Crackers', 'Snacks', 'Crackers', false, true, 3.49, null, 'Crix', 'Jamaica'),
('Eclipse Crackers', 'Snacks', 'Crackers', false, true, 3.49, null, 'Eclipse', 'Jamaica'),
('Cassava Chips', 'Snacks', 'Cassava chips', false, true, 3.49, null, null, null),
('Dried Agbalumo (star apple)', 'Snacks', 'Dried fruit', false, true, 7.99, null, null, 'Trinidad'),
('Super 2 Biscuit', 'Snacks', 'Biscuits', false, true, 2.49, null, null, null),
('Nestlé Digestive/Cabin Biscuit', 'Snacks', 'Biscuits', false, true, 2.99, null, 'Nestlé', 'Nigeria'),
('Nasco Wafer', 'Snacks', 'Wafer', false, true, 2.49, null, 'Nasco', 'Nigeria'),
('D&G Ting Grapefruit Soda 300ml', 'Beverages', 'Soda', false, true, 1.99, null, 'Ting', 'Jamaica'),
('D&G Kola Champagne 591ml', 'Beverages', 'Soda', false, true, 1.99, null, 'D&G', 'Jamaica'),
('D&G Pineapple Soda', 'Beverages', 'Soda', false, true, 1.79, null, 'D&G', 'Jamaica'),
('Malta Guinness 330ml', 'Beverages', 'Malt drink', false, true, 2.49, null, 'Malta Guinness', 'Nigeria'),
('Vitamalt 330ml', 'Beverages', 'Malt drink', false, true, 2.29, null, 'Vitamalt', null),
('Nestlé Milo Chocolate Powder 400g', 'Beverages', 'Chocolate drink', false, true, 8.99, null, 'Nestlé', 'Nigeria'),
('Milo 3.3lb', 'Beverages', 'Chocolate drink', false, true, 26.99, null, 'Milo', null),
('Ovaltine Malt Mix', 'Beverages', 'Malt drink mix', false, true, 7.99, null, 'Ovaltine', null),
('Ketepa Tea (Kenyan)', 'Beverages', 'Tea', false, true, 6.99, null, 'Ketepa', 'Kenya'),
('Lipton Yellow Label Tea', 'Beverages', 'Tea', false, true, 4.99, null, 'Lipton', null),
('Old Jamaica Ginger Beer', 'Beverages', 'Soda', false, true, 1.99, null, 'Old Jamaica', 'Jamaica'),
('Dried Hibiscus (Zobo) Leaves', 'Beverages', 'Zobo/sorrel', false, true, 6.99, null, null, 'Nigeria'),
('Peardrax Sparkling Pear (Trini)', 'Beverages', 'Soda', false, true, 2.49, null, 'Peardrax', 'Trinidad'),
('Solo Kola Champagne (Trini)', 'Beverages', 'Soda', false, true, 2.29, null, 'Solo', 'Trinidad'),
('Grace Coconut Water', 'Beverages', 'Coconut water', false, true, 2.49, null, 'Grace', 'Jamaica'),
('Ethiopian Yirgacheffe Coffee 340g', 'Beverages', 'Coffee', false, true, 19.99, null, null, 'Ethiopia'),
('Yellow Cornmeal (Grace) 2lb', 'Baking', 'Cornmeal', false, true, 3.99, null, 'Grace', 'Jamaica'),
('Fine Cornmeal', 'Baking', 'Cornmeal', false, true, 3.49, null, null, null),
('All Purpose Flour (JF Mills) 1kg', 'Baking', 'Wheat flour', false, true, 3.99, null, null, null),
('Festival/Fritter Mix', 'Baking', 'Baking mix', false, true, 4.99, null, null, 'Jamaica'),
('Blue Bird Baking Powder', 'Baking', 'Leavening', false, true, 2.49, null, 'Blue Bird', null),
('Grace Vanilla Essence', 'Baking', 'Essence', false, true, 2.99, null, 'Grace', 'Jamaica'),
('Grace Brown Cane Sugar 907g', 'Baking', 'Sugar', false, true, 5.5, null, 'Grace', 'Jamaica'),
('Whole Nutmeg', 'Baking', 'Spice', false, true, 4.99, null, null, null),
('Indomie Chicken Flavour (single 70g)', 'Noodles & Pasta', 'Instant noodles', false, true, 0.99, null, 'Indomie', 'Nigeria'),
('Indomie Mi Goreng (30 pk case)', 'Noodles & Pasta', 'Instant noodles', false, true, 29.99, null, 'Indomie', 'Nigeria'),
('Indomie Hungry Man Size', 'Noodles & Pasta', 'Instant noodles', false, true, 1.99, null, 'Indomie', 'Nigeria'),
('Chief Chowmein Noodles 16oz', 'Noodles & Pasta', 'Chowmein', false, true, 2.89, null, 'Chief', 'Trinidad'),
('Guyana Tasty Chowmein 12oz', 'Noodles & Pasta', 'Chowmein', false, true, 1.99, null, 'Guyana Tasty', 'Guyana'),
('Grace Macaroni/Pasta', 'Noodles & Pasta', 'Pasta', false, true, 2.49, null, 'Grace', 'Jamaica'),
('Baasto (Somali spaghetti)', 'Noodles & Pasta', 'Pasta', false, true, 2.99, null, null, 'Somalia'),
('Dudu Osun Black Soap', 'Household', 'Soap', false, true, 4.19, null, 'Dudu Osun', 'Nigeria'),
('African Net Sponge (Sapo)', 'Household', 'Bath sponge', false, true, 4.99, null, null, 'West Africa'),
('Chewing Stick (Pako)', 'Household', 'Oral care', false, true, 3.99, null, null, 'West Africa'),
('Dettol Antibacterial Soap 100g', 'Household', 'Soap', false, true, 1.19, null, 'Dettol', 'Caribbean'),
('Dutch Pot (aluminum)', 'Household', 'Cookware', false, true, 39.99, null, null, 'Caribbean'),
('Nigerian Raw Honey', 'Household', 'Honey', false, true, 14.99, null, null, 'Nigeria'),
('Shea Butter (cosmetic)', 'Household', 'Body care', false, true, 9.99, null, null, null);
